# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0ac116b91c73391637da3d654209487a"
name = "EmbedUp - Sell anywhere"
handle = "embedup"
application_url = "https://app.embedup.com/"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"


  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  
[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_resource_feedbacks,read_publications,unauthenticated_read_checkouts,unauthenticated_read_product_inventory,unauthenticated_read_product_listings,unauthenticated_write_checkouts,write_products"

[auth]
redirect_urls = ["https://app.embedup.com/auth/callback", "https://app.embedup.com/auth/shopify/callback", "https://app.embedup.com/api/auth/callback"]

[pos]
embedded = false
