# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f96d7136a6d4dd93b083a85e08ec9221"
name = "embedupdev - sell anywhere"
handle = "embedupdev"
application_url = "https://app.shopcomponent.com/"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"


  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  
[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_resource_feedbacks,read_publications,unauthenticated_read_checkouts,unauthenticated_read_product_inventory,unauthenticated_read_product_listings,unauthenticated_write_checkouts,write_products"

[auth]
redirect_urls = ["https://app.shopcomponent.com/auth/callback", "https://app.shopcomponent.com/auth/shopify/callback", "https://app.shopcomponent.com/api/auth/callback"]

[pos]
embedded = false
