[[extensions]]
name = "embedup trigger"
handle = "embedup-trigger"
type = "flow_trigger"
uid = "56b033e5-6cb9-da6a-c6b1-08d72c5a09adfd26ed05"
description = "trigger will run when new component is created"

[settings]

  [[settings.fields]]
  type = "email"
  key = "email"

  [[settings.fields]]
  type = "single_line_text_field"
  key = "component"
